# Form implementation generated from reading ui_qt file 'aboutdialog.ui_qt'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_AboutDialog(object):
    def setupUi(self, AboutDialog):
        AboutDialog.setObjectName("AboutDialog")
        AboutDialog.resize(500, 350)
        self.verticalLayout = QtWidgets.QVBoxLayout(AboutDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_title = QtWidgets.QLabel(parent=AboutDialog)
        self.label_title.setTextFormat(QtCore.Qt.TextFormat.RichText)
        self.label_title.setAlignment(QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_title.setObjectName("label_title")
        self.verticalLayout.addWidget(self.label_title)
        self.label_info = QtWidgets.QLabel(parent=AboutDialog)
        self.label_info.setWordWrap(True)
        self.label_info.setOpenExternalLinks(True)
        self.label_info.setObjectName("label_info")
        self.verticalLayout.addWidget(self.label_info)
        self.label_description = QtWidgets.QLabel(parent=AboutDialog)
        self.label_description.setWordWrap(True)
        self.label_description.setObjectName("label_description")
        self.verticalLayout.addWidget(self.label_description)
        self.label_license = QtWidgets.QLabel(parent=AboutDialog)
        self.label_license.setTextFormat(QtCore.Qt.TextFormat.RichText)
        self.label_license.setAlignment(QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.label_license.setObjectName("label_license")
        self.verticalLayout.addWidget(self.label_license)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=AboutDialog)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(AboutDialog)
        QtCore.QMetaObject.connectSlotsByName(AboutDialog)

    def retranslateUi(self, AboutDialog):
        _translate = QtCore.QCoreApplication.translate
        AboutDialog.setWindowTitle(_translate("AboutDialog", "About"))
        self.label_title.setText(_translate("AboutDialog", "App Name"))
        self.label_info.setText(_translate("AboutDialog", "Version, Author, Email, Website"))
        self.label_description.setText(_translate("AboutDialog", "Description"))
        self.label_license.setText(_translate("AboutDialog", "License"))
