# Form implementation generated from reading ui_qt file 'mainwindow.ui_qt'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(500, 500)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.search_bar = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.search_bar.setObjectName("search_bar")
        self.verticalLayout.addWidget(self.search_bar)
        self.list_widget = QtWidgets.QListWidget(parent=self.centralwidget)
        self.list_widget.setObjectName("list_widget")
        self.verticalLayout.addWidget(self.list_widget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.main_toolbar = QtWidgets.QToolBar(parent=MainWindow)
        self.main_toolbar.setMovable(False)
        self.main_toolbar.setIconSize(QtCore.QSize(32, 32))
        self.main_toolbar.setObjectName("main_toolbar")
        MainWindow.addToolBar(QtCore.Qt.ToolBarArea.TopToolBarArea, self.main_toolbar)
        self.new_action = QtGui.QAction(parent=MainWindow)
        self.new_action.setObjectName("new_action")
        self.bin_action = QtGui.QAction(parent=MainWindow)
        self.bin_action.setObjectName("bin_action")
        self.main_toolbar.addAction(self.new_action)
        self.main_toolbar.addAction(self.bin_action)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Ubuntu Sticky Notes"))
        self.search_bar.setPlaceholderText(_translate("MainWindow", "Search..."))
        self.new_action.setText(_translate("MainWindow", "New Note (Shift + N)"))
        self.bin_action.setText(_translate("MainWindow", "Trash"))
