# Form implementation generated from reading ui_qt file 'stickywindow.ui_qt'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_StickyWindow(object):
    def setupUi(self, StickyWindow):
        StickyWindow.setObjectName("StickyWindow")
        StickyWindow.resize(500, 500)
        self.verticalLayout = QtWidgets.QVBoxLayout(StickyWindow)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.headerLayout = QtWidgets.QHBoxLayout()
        self.headerLayout.setContentsMargins(3, 3, 3, 4)
        self.headerLayout.setSpacing(3)
        self.headerLayout.setObjectName("headerLayout")
        self.header_bar_panel = QtWidgets.QWidget(parent=StickyWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.header_bar_panel.sizePolicy().hasHeightForWidth())
        self.header_bar_panel.setSizePolicy(sizePolicy)
        self.header_bar_panel.setMinimumSize(QtCore.QSize(10, 24))
        self.header_bar_panel.setMaximumSize(QtCore.QSize(16777215, 24))
        self.header_bar_panel.setObjectName("header_bar_panel")
        self.headerBarLayout = QtWidgets.QHBoxLayout(self.header_bar_panel)
        self.headerBarLayout.setContentsMargins(0, 0, 0, 0)
        self.headerBarLayout.setObjectName("headerBarLayout")
        self.btn_add = QtWidgets.QPushButton(parent=self.header_bar_panel)
        self.btn_add.setMaximumSize(QtCore.QSize(30, 30))
        self.btn_add.setFlat(True)
        self.btn_add.setObjectName("btn_add")
        self.headerBarLayout.addWidget(self.btn_add)
        spacerItem = QtWidgets.QSpacerItem(30, 30, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.headerBarLayout.addItem(spacerItem)
        self.btn_pin = QtWidgets.QPushButton(parent=self.header_bar_panel)
        self.btn_pin.setMaximumSize(QtCore.QSize(30, 30))
        self.btn_pin.setFlat(True)
        self.btn_pin.setObjectName("btn_pin")
        self.headerBarLayout.addWidget(self.btn_pin)
        self.btn_close = QtWidgets.QPushButton(parent=self.header_bar_panel)
        self.btn_close.setMaximumSize(QtCore.QSize(30, 30))
        self.btn_close.setFlat(True)
        self.btn_close.setObjectName("btn_close")
        self.headerBarLayout.addWidget(self.btn_close)
        self.headerLayout.addWidget(self.header_bar_panel)
        self.verticalLayout.addLayout(self.headerLayout)
        self.text_container = QtWidgets.QWidget(parent=StickyWindow)
        self.text_container.setObjectName("text_container")
        self.textContainerLayout = QtWidgets.QVBoxLayout(self.text_container)
        self.textContainerLayout.setContentsMargins(5, 5, 5, 5)
        self.textContainerLayout.setObjectName("textContainerLayout")
        self.text_edit = QtWidgets.QTextEdit(parent=self.text_container)
        self.text_edit.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.CustomContextMenu)
        self.text_edit.setStyleSheet("background: transparent; border: none; font-size: 12pt;")
        self.text_edit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.text_edit.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.text_edit.setObjectName("text_edit")
        self.textContainerLayout.addWidget(self.text_edit)
        self.verticalLayout.addWidget(self.text_container)

        self.retranslateUi(StickyWindow)
        QtCore.QMetaObject.connectSlotsByName(StickyWindow)

    def retranslateUi(self, StickyWindow):
        _translate = QtCore.QCoreApplication.translate
        StickyWindow.setWindowTitle(_translate("StickyWindow", "Sticky Note"))
        self.btn_add.setText(_translate("StickyWindow", "+"))
        self.btn_pin.setText(_translate("StickyWindow", "!"))
        self.btn_close.setText(_translate("StickyWindow", "✕"))
