# Form implementation generated from reading ui_qt file 'trashwindow.ui_qt'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_TrashWindow(object):
    def setupUi(self, TrashWindow):
        TrashWindow.setObjectName("TrashWindow")
        TrashWindow.resize(400, 500)
        self.verticalLayout = QtWidgets.QVBoxLayout(TrashWindow)
        self.verticalLayout.setObjectName("verticalLayout")
        self.list_widget = QtWidgets.QListWidget(parent=TrashWindow)
        self.list_widget.setObjectName("list_widget")
        self.verticalLayout.addWidget(self.list_widget)

        self.retranslateUi(TrashWindow)
        QtCore.QMetaObject.connectSlotsByName(TrashWindow)

    def retranslateUi(self, TrashWindow):
        _translate = QtCore.QCoreApplication.translate
        TrashWindow.setWindowTitle(_translate("TrashWindow", "Trash"))
