name: linsticky
base: core24
version: '2.0.1'
summary: Lightweight and elegant sticky notes for your Linux desktop.
license: MIT
description: |
              LinSticky is a simple, modern, and lightweight sticky notes application designed for Linux. It provides a clean way to keep your reminders, tasks, and ideas right on your desktop.
              
              ✨ Key Features:
              
                  📝 Smart Notes: A sleek, minimalist interface built with Python and GTK4 for maximum focus.
              
                  📌 Pin to Top: Keep your essential tasks anchored and always visible.
              
                  🎨 Personalization: Organize your thoughts with a custom color palette.
              
                  ✍️ Formatting: Full support for rich text preservation (bold, italics, lists).
              
                  🐧 Native Experience: Built with Libadwaita to look perfect on GNOME and other modern desktops.
              
                  🌍 Multilingual: Fully localized in English, Español, Deutsch, Français, Русский, Қазақша, and more.
              
              If you are looking for a simple "post-it" style experience for Linux, LinSticky is the perfect tool for your daily workflow.

grade: devel
confinement: strict
icon: linsticky/resources/icons/app.png

parts:
  linsticky:
    plugin: dump
    source: .
    stage:
      - -build_deb_package.sh
      - -compile_translations.sh
      - -create_translation.sh
      - -generate_translations.sh
      - -update_translation.sh
      - -linsticky_2.0.0-beta3_all.deb
      - -linsticky_deb
      - -parts
      - -prime
      - -stage
      - -.venv
      - -.idea
      - -.git
      - -__pycache__
    stage-packages:
      - python3
      - python3-gi
      - python3-cairo
      - gir1.2-adw-1
      - gir1.2-ayatanaappindicator3-0.1

    override-prime: |
      craftctl default
      mkdir -p $CRAFT_PRIME/usr/bin
      if [ ! -f "$CRAFT_PRIME/usr/bin/python3" ]; then
        ln -s /usr/bin/python3 $CRAFT_PRIME/usr/bin/python3
      fi

slots:
  dbus-linsticky:
    interface: dbus
    bus: session
    name: io.linsticky.app

apps:
  linsticky:
    command: usr/bin/python3 $SNAP/linsticky/main.py
    desktop: snap/gui/io.linsticky.app.desktop
    extensions:
      - gnome
    slots:
      - dbus-linsticky
    plugs:
      - home
      - unity7
      - gsettings
      - network
