name: linsticky
base: core24
version: '2.0.1'
summary: Modern sticky notes application.
description: |
  ✨ Features
  📝 **Smart Sticky Notes**
  Experience a clutter-free environment. Create and manage your thoughts with a sleek, minimalist interface optimized for maximum focus and efficiency.

  📌 **Pinned Notes**
  Never lose track of what matters. Keep your high-priority tasks and essential information anchored at the top for instant access.

  🎨 **Custom Color Palette**
  Bring color to your productivity. Personalize your workflow.

  ✍️ **Rich Text Preservation**
  Bold, italics, and lists are saved exactly as you typed them.

  🖥️ **Modern GNOME Experience**
  Built with Python, GTK4, and Libadwaita.

  🌍 **Global by Design**
  Fully localized: English, Русский, Қазақша, and more.

grade: devel
confinement: strict
icon: linsticky/resources/icons/app.png

parts:
  linsticky:
    plugin: dump
    source: .
    stage:
      - -build_deb_package.sh
      - -compile_translations.sh
      - -create_translation.sh
      - -generate_translations.sh
      - -update_translation.sh
      - -linsticky_2.0.0-beta3_all.deb
      - -linsticky_deb
      - -parts
      - -prime
      - -stage
      - -.venv
      - -.idea
      - -.git
      - -__pycache__
    stage-packages:
      - python3
      - python3-gi
      - python3-cairo
      - gir1.2-adw-1
      - gir1.2-ayatanaappindicator3-0.1

    override-prime: |
      craftctl default
      mkdir -p $CRAFT_PRIME/usr/bin
      if [ ! -f "$CRAFT_PRIME/usr/bin/python3" ]; then
        ln -s /usr/bin/python3 $CRAFT_PRIME/usr/bin/python3
      fi

slots:
  dbus-linsticky:
    interface: dbus
    bus: session
    name: io.linsticky.app

apps:
  linsticky:
    command: usr/bin/python3 $SNAP/linsticky/main.py
    desktop: snap/gui/io.linsticky.app.desktop
    extensions:
      - gnome
    slots:
      - dbus-linsticky
    plugs:
      - home
      - unity7
      - gsettings
      - network
